world:
  world_height: 10  #13
  world_width: 10   # 13
  step_time: 0.1
  xy_resolution: 0.1 # 0.01 # meter
  yaw_resolution: 5 # degree
  init_point: [0, 0, 0]
  # world_map: 'map_100_100.png'
  # world_map: 'cave.png'

robots:
  robot_number: 4
  robot_mode: 'diff'  # omni or diff
  robot_init_mode: 0 # 0 custom, 1 single row, 2, random, 3 circle
  init_state_list: [[1, 1, 1.57], [8, 9, 3.14],[2, 1, 0], [9, 9,-1.57]]
  goal_list: [[8, 9, 0], [1, 1, 0],[2, 9, 0], [8, 2, 0]]
  radius_list: [0.2, 0.2,0.2, 0.2]
  vel_max: [1.5, 1.5]
  radius_exp: 0.1

obs_cirs:
  number: 4
  dist_mode: 0
  obs_model: 'dynamic' # static, dynamic 
  obs_step_mode: 'default' # default, wander
  obs_state_list: [[4.5, 6.4], [5.5, 5.6],[7.5, 6.4], [4.5, 4.6]]
  obs_goal_list: [[4.5, 2.4], [1.5, 3.6],[4.5, 2.4], [1.5, 3.6]]
  obs_radius_list: [0.2, 0.3,0.4,0.25]
  obs_square: [2, 2, 8, 8]  #正方形运动区域
  obs_interval: 0.5
  random_radius: true
  vel_max: [1, 1]


obs_lines:
  obs_line_states: [
    # 边界
    [0, 0, 0, 10], [0, 10, 10, 10],[10, 10, 10, 0],[10, 0, 0, 0], 

    # [2, 2, 1, 2], [1, 2, 1, 3],[1, 3, 2, 3],[2, 3, 2, 2],
    # [3,6,3,7],[3,7,4,7]
    ]
  
  
  
