
world:
  world_height: 10  #13
  world_width: 10   # 13
  step_time: 0.1
  xy_resolution: 0.1 # 0.01 # meter
  yaw_resolution: 5 # degree
  init_point: [0, 0, 0]
  # world_map: 'cave2.png'

robots:
  robot_number: 4
  robot_mode: 'diff'  # omni or diff
  robot_init_mode: 0 # 0 custom, 1 single row, 2, random, 3 circle
  # init_state_list: [[1, 1, 0], [3, 1, 0],[5, 1, 0], [7, 1, 0]]
  # goal_list: [[1, 8, 0], [3, 8, 0],[5, 8, 0], [7, 8, 0]]
  init_state_list: [[1, 1, 0], [6, 3, 0],[3, 1, 0], [8, 3, 0]]
  goal_list: [[6, 7, 0], [5, 4, 0],[4, 4, 0], [3, 9, 0]]
  # init_state_list: [[1, 1, 0], [6, 3, 0],[3, 9, 0], [4, 7, 0]]
  # goal_list: [[6, 7, 0], [1, 4, 0],[4, 4, 0], [3, 9, 0]]
  radius_list: [0.2, 0.2,0.2, 0.2]
  vel_max: [1.5, 1.5]
  radius_exp: 0.1

obs_lines:
  obs_line_states: [
    # 边界
    [0, 0, 0, 10], [0, 10, 10, 10],[10, 10, 10, 0],[10, 0, 0, 0], 

    # [2, 2, 1, 2], [1, 2, 1, 3],[1, 3, 2, 3],[2, 3, 2, 2],
    # [3,6,3,7],[3,7,4,7]
    ]
  

  
  
  
  
